### PR TITLE
add/edit way mode

### PR DESCRIPTION
**Pull request by sethvincent**
This adds a way editing mode to the explore screen. This added two new modes: one for adding ways, one for editing ways. It seemed like a good time to organize the mode switching somewhat to make it a little clearer. Primarily this meant implementing and using a `mapModes` object: https://github.com/developmentseed/observe/compare/way-editing-mode?expand=1#diff-151db68c781d309cbd0c2ffa7b9df353

Before merging this I need to fix the mode-related tests.

This pr really just focuses on implementing the new modes and a working button for entering the `Add Way` mode:

Screen Shot 2020-02-10 at 3 30 30 PM
Screen Shot 2020-02-10 at 3 30 38 PM

Immediate next steps that could happen in this pr or another:

- better managing the action buttons in the bottom right side of the screen based on `mode`
- more appropriate icon for the add way button
- implementing the flow of tapping the plus button, then choosing to tap the point, way, photo, or trace button

### CODE REVIEW

**Comment by geohacker** [comment]
@sethvincent this is looking really good to me. Like you mentioned, it might be nice to fix the button management as part of this PR. We can come back to icons later.

**Comment by sethvincent** [comment]
updated tests & the button behavior. the ways action button(s) are still unimplemented and can happen in a followup pr.

screengif 2020-02-11 at 17 21 39

I think this is ready to merge, but feel free to make/suggest changes.

**Comment by LanesGood** [comment]
@sethvincent I've added in animation on the FAB menu, but in doing so I've introduced issues with the mode buttons, which can now not be pressed. It seems that there is an issue wrapping `Animated.View` in `TouchableHighlight`, combined with the absolute positioning and animating `TranslateY` property..

In the screen recording, I'm trying to click the mode buttons with no effect
observe-menu-animated1

I think this should be easy to solve, and simply has to do with solving the wrapping and positioning issues. The `Explore.js` screen could also now be cleaned up, and the MegaMenu should probably be split out as a component.

**Comment by geohacker** [comment]
@LanesGood this is really cool! Thank you! I'll ticket that we should break the MegaMenu into it's own component and merge this PR.

**Pull request merged**
