### PR TITLE
Fix preset icons

### PR DESCRIPTION
**Pull request by vgeorge**
See #225. Scripts `update-icons.sh` and `link-icons.sh` were updated to include icons from [iD presets](https://github.com/openstreetmap/iD/tree/develop/svg/iD-sprite/presets). @geohacker, is there any additional command I should run after linking the new files? Both Android and iOS can't build the app now.

### CODE REVIEW

**Comment by geohacker** [comment]
@vgeorge thank you. I can reproduce that the app crashes right after launching. I ran the update-icon.sh script and still have this problem.

When I tried to build using xcode, I got this:

```
2020-05-21 13:08:26.820555+0530 Observe[63922:6263865] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Cannot assign nil image to “iD_operation_reflect_long”.'
```

Will continue inspecting

**Comment by geohacker** [comment]
Ok I fixed that. We were trying to fetch icons that weren't available in the assets folder. The last thing to do here is to update the Observe Icons font here https://github.com/developmentseed/observe-icon-font - I can do that now.

**Comment by geohacker** [comment]
image

I made a PR against observe-icon-font and tested https://github.com/developmentseed/observe-icon-font/pull/1

@vgeorge this is my bad that I didn't think of observe-icon-font. In fact, we don't have to add these iD icons into Observe as assets as they are not used on the map. It's alright for now. Thank you again for setting this up.

**Comment by sethvincent** [comment]
I added a commit to update observe-icon-font. i think this is now ready.

**Pull request merged**
