### PR TITLE
Icon, trace/photo & dialogue styles

### PR DESCRIPTION
**Pull request by LanesGood**
Modifies styles for icons, text in traces + photos and base map buttons
TODO 
- [x] make recordheader push top buttons down, and push all other containers down
- [ ] (In separate branch) "speed dial" aka combine action buttons

Locate and basemap layer buttons resized and repositioned:
Screen Shot 2019-11-20 at 5 16 57 PM

Screen Shot 2019-11-20 at 5 17 08 PM
Screen Shot 2019-11-20 at 5 16 46 PM

contributes to #45

### CODE REVIEW

**Comment by LanesGood** [comment]
The recording header now pushes down the rest of the viewport while recording. This also allows users to add points and take pictures while recording a track without obscuring those screens.

image

image

image

One thing I'd like confirmation on is whether the rest of the screen still scrolls correctly in the "Save Picture" screen.

**Comment by geohacker** [comment]
@LanesGood this is looking really good!

> One thing I'd like confirmation on is whether the rest of the screen still scrolls correctly in the "Save Picture" screen.

This works, I'm adding a bit of additional scroll for the scrollview so it looks alright.

One main issue I noticed is the now on iOS (iPhone 11 pro), I can't see the MapOverlay when I select a feature from the map: 

IMG_8970

**Comment by geohacker** [comment]
@LanesGood I think I managed to fix it by increasing the drawer offset. Let me know what you think!

**Comment by geohacker** [comment]
I think we've to make the overlay offset respect the header height.

**Comment by LanesGood** [comment]
@geohacker fixed the drawer overlay by pulling it outside of the mainBody component. Hopefully this doesn't cause any peripheral issues with the "Add Point" overlay - I haven't seen any issues so far. I reverted the drawer offset once this was done.
image


I first tried passing in the recordingStatus to the mapOverlay drawer, and then setting the offset like so:
`offset={recording === 'recording' || 'paused' ? 140 + headerHeight.height : 120}`
but this wasn't working, so I took the more drastic option above.

**Comment by geohacker** [comment]
@LanesGood this works really well!

**Pull request merged**
