### PR TITLE
actions and reducers for edit way logic

### PR DESCRIPTION
**Pull request by batpad**
Creating a PR as we start to sketch out the logic of the actions and reducers for the edit way component.

### CODE REVIEW

**Comment by sethvincent** [comment]
This is now in a state where a user can navigate to adding a way, add points to a way, and then move to selecting a preset and editing tags. The rendering style is still very much in the early stages and only works with LineStrings so far.

@geohacker

**Comment by sethvincent** [comment]
latest commit does two things:
- fixes the crosshair position. new nodes were being added at the top of the crosshair rather than the middle, which had unexpected results
- adds actions for undo/redo. this mostly works, but there is a weird behavior where the current state (the present) is also put into the history (the past) whenever a new node is added, resulting in the user needing to press undo twice to actually undo the first time. this is confusing and seems like a bug with [redux-undo](https://github.com/omnidan/redux-undo). how can the present also be in the past.

**Comment by sethvincent** [comment]
@geohacker my latest commit does a few things:
- removes redux-undo package and replaces it with a simpler implementation that's easier to work with in this case
- splits the previous `currentWayEdit` action/reducer files into two: `wayEditingHistory` that provides the state that can undo/redo, and `wayEditing` for managing any other state that shouldn't be tracked in the undo/redo system
- renders the nodes in a way by (for now) hijacking the `nodesGeojson` layer when in way add/edit mode
- gets the logic for selecting a node in the way to about 90% of the way done. i think it might just need the style for a selected node to be fixed up. i started reusing the shape/style/filter for selected photos but didn't get all the way done with that

undo/redo now works properly, and this takes care of the dependencies needed to get node moving/deleting implemented.

**Comment by sethvincent** [comment]
Latest commits add the ability to delete and move nodes in a way. It's currently limited to only working with one node at a time. Deleting multiple nodes at once could be possible, but moving more than one would be relatively tricky.

I'm not entirely satisfied with the interactions for moving a node. We should test this with folks and see how it goes.

I tried to add filters for the selected/unselected nodes and clearly have no idea what I'm doing. Currently there's an error when selecting a node because of the style, so I'm still debugging this.

**Comment by geohacker** [comment]
@sethvincent thank you so much for your work on this PR. This is looking really good to me. I think we should merge this now and open a new PR for next steps.

**Pull request merged**
