### PR TITLE
Photos list screen

### PR DESCRIPTION
**Pull request by geohacker**
This PR creates a list view for photos taken by the user that are available on the device.

### CODE REVIEW

**Comment by LanesGood** [comment]
@geohacker per comments on the navigation, the photo list screen follows the "Your Contributions" UI. This is now mocked up here:
https://invis.io/CGUB4COZKTB#/389875876_your-Photos--list

**Comment by geohacker** [comment]
I think this branch is ready for review + merge. It contains the following screens:

image

image

image

image

**Comment by geohacker** [comment]
@sethvincent Ah yes, I should have mentioned. I have not wired those up yet. The photo marker -> screen needs an intermediate step to add them to the bottom drawer. I'll do that in a separate PR.

**Comment by batpad** [comment]
@geohacker this seems to work well for me on device!

I had very minor issues with the Description field and the keyboard. The keyboard seemed to *sometimes* overlap on top of the input a bit. This was hard to reliably reproduce and even when it occurred, it was still completely usable. I would vote to merge this, and if the issue with the text input crops up, make a separate ticket.

**Pull request merged**
