### PR TITLE
Update map color variables

### PR DESCRIPTION
**Pull request by LanesGood**
This PR adds the app color theme to OSM features on the map. Goal here was to align with the mockup, make the app brand colors more dominant, and emphasize selected over background features. To review: color selection, ability to distinguish actions and feature types.

Screen Shot 2020-05-18 at 3 38 18 PM

### CODE REVIEW

**Comment by geohacker** [comment]
@LanesGood thank you! This looks really good, I'll test a bit more today. My only thought is do we need to worry about changing existing styles that the app shipped with? It takes a bit of time to update all the screenshots and readme, but if you think it won't be disorienting to users I'm in favour 👍

**Comment by LanesGood** [comment]
@geohacker it could be a bit disorienting, though we've introduced multiple new features without updating users. On that note, how difficult would it be to introduce a changelog modal? Eventually, for a full production release I'd like to see us implement walkthroughs, an in-app new user guide, and more structured release notes.

For now, I'm happy to help with screenshots for the user guide - just let me know how/when to split these up.

**Comment by geohacker** [comment]
@LanesGood this looks and works great. One last thing: the `nearest` nodes here https://github.com/developmentseed/observe/blob/custom-map-colors/app/screens/Explore.js#L717 have the same style as the nodes of the currently editing way. This sometimes is confusing. For example - I want to see the node I'm snapping to which exists on the way vs a new node that will be created when I snap. 

If you can create style for this, I can apply a filter on the nearestNodes based on the `id`. The `id` of new node will start with `observe-`

**Comment by LanesGood** [comment]
@geohacker updated styles to distinguish nearestNode, and de-emphasize unselected buildings.

Actively editing way: larger node circle, white stroke, 100% opacity. 
Nearest nodes: smaller circle, dark stroke, 50% opacity
Screen Shot 2020-05-19 at 12 33 19 PM
Screen Shot 2020-05-19 at 12 30 57 PM
Screen Shot 2020-05-19 at 12 30 18 PM
Screen Shot 2020-05-19 at 12 28 05 PM
Screen Shot 2020-05-19 at 12 27 50 PM

**Pull request merged**
