### PR TITLE
revise ios version script to use agvtool, keep android version code in sync with ios build version

### PR DESCRIPTION
**Pull request by sethvincent**
I was trying to create a new build today and ran into the ios-version script no longer working because of changes to the Info.plist.

We're using `CURRENT_PROJECT_VERSION` in Info.plist now so the script was pulling that as the value to try and increment it.

```
./version-ios.sh: line 10: $(CURRENT_PROJECT_VERSION) + 1: syntax error: operand expected (error token is "$(CURRENT_PROJECT_VERSION) + 1")
```

I looked into it a bit and tried out the methods described here: https://medium.com/xcblog/agvtool-automating-ios-build-and-version-numbers-454cab6f1bbe

This uses `agvtool` to update the marketing and build version numbers. The marketing number is the version from package.json and the build number automatically increments.

From what I can tell this does what we need, though I'm not sure if there's anything else that needs to be changed.

### CODE REVIEW

**Comment by geohacker** [comment]
@sethvincent this is a good way to solve the version issue, but I had trouble with the CFBundleShortVersionString while creating a build that can be uploaded to TestFlight/App Store. The ipa upload to App Store always failed with an error saying `CFBundleShortVersionString ` is invalid and can't have non-numeric. I fixed this by removing `-alpha`. This was the recommended solution :-/ https://github.com/developmentseed/observe/pull/160/files#diff-5fabd8dce09a05911cdac1b3610dd50dL20

I think if we can make agvtool always take the semver part of the version string, that would be the ideal fix.

**Comment by sethvincent** [comment]
Ah, right. I guess in the case of the release I was trying to do maybe I would only need to increment the build number, not the `CFBundleShortVersionString`. Maybe in general we can just use build numbers instead of trying to use the `-alpha` versioning style.

**Comment by sethvincent** [comment]
I've made a few more changes here to try and simplify things. The more I hack on this the more it seems best to stop using the `-alpha` style strings in versions and just use build numbers.

This pr now:

- keeps ios build version and android version code the same. this has an important side effect that I'll describe below
- adds a build-version.sh script for incrementing the build version / version code separately from the semver version number.
- simplifies the version management by using agvtool for ios and adding a version.properties file for android that gets called/updated via the version hook when calling `npm version {version}`

In practice this doesn't change a whole lot about how we create builds. It means that rather than having 0.2.0-alpha and then 0.2.0, we'll have a 0.2.0 release with incremental/alpha builds that are tested for quality assurance (with build numbers of say 12-15 or whatever) and then when we are confident that a build has all the needed fixes, we release build 16 (or whatever the build number ends up being) as the final 0.2.0 release.

We can still refer to builds leading up to the final 0.2.0 release as alpha or beta builds, just not in the formal versioning system.

### Breaking change

I've changed this:

```
versionCode versionMajor * 10000 + versionMinor * 100
```

To instead match the `CURRENT_BUILD_VERSION` that's used in ios. I'm pretty sure that I somehow introduced this weird `versionMajor * 10000 + versionMinor * 100` version code but I'm not sure why or how. I think it would be best for this to match the ios build version instead. Keeping the android version code separate from the semver version also allows us to use the version code how it was meant to be used, an incremental build number.

This change means that before installing the next version of the app, users will need to first delete the old one (but only this one time). I think that's an ok tradeoff. Better to get this versioning a little more organized now rather than later.

**Comment by geohacker** [comment]
This looks good to me @sethvincent, thank you!

**Pull request merged**
