### PR TITLE
show deleted ways

### PR DESCRIPTION
**Pull request by geohacker**
This PR completes #296 
cc @LanesGood

### CODE REVIEW

**Comment by LanesGood** [comment]
@geohacker  it appears the last two nodes of the way still exist, even though the way itself is deleted.  Can you confirm whether this is expected behavior?

**Comment by geohacker** [comment]
@LanesGood yes, that's right. That's how deleted POIs also show up so I just matched the same. There'll be `pendingDeleteUpload = true` property on these features. So we could style these differently.

**Comment by LanesGood** [comment]
@geohacker this is the current case of deleting two nodes from a 4-node closed polygon:

way-poly-delete

Should we aim instead for the iD behavior for deleting a closed feature entirely if there are not three nodes?

**Comment by geohacker** [comment]
> Should we aim instead for the iD behavior for deleting a closed feature entirely if there are not three nodes?

Thanks for pointing this out @LanesGood. I checked iD again and it's doing what you recommended. Deleting the way if it's a polygon and less than 3 nodes. @batpad do you think this will fit within the workflow of how we manage lines?

**Pull request merged**
