### PR TITLE
add photos to a feature

### PR DESCRIPTION
**Pull request by geohacker**
* [x] add a photo in the EditFeatureDetailScreen
* [x] view all photos associated to this feature in ViewFeatureDetailScreen

### CODE REVIEW

**Comment by geohacker** [comment]
feature-photo-grid

**Comment by geohacker** [comment]
> the photo thumbnail doesn't always seem to save.

@LanesGood thank you for testing this. I'm unfortunately not able to reproduce the behaviour you mentioned -- test on both iOS and Android simulator/emulator. Could you perhaps try to reproduce and note down the steps?

**Comment by batpad** [comment]
I was unable to reproduce any of the issues with the thumbnailing - testing on my android device, was able to take photos from the Edit Feature Detail screen, had the thumbnails show up fine, scrolling through many worked fine, and showing up in the Photos List screen worked fine.

I did feel the similar confusion when Adding the Photo and not needing to Save / enter changeset comment as with other "Edits". Of course, it makes sense, but I wonder if we have considered / should consider having the Add Photo right on the View Feature Detail screen instead of Edit Feature Detail - and then it's clearly a distinct action from editing feature attributes. @LanesGood I think whatever you feel is best here.

This worked well for me @geohacker - we can wait to see if @LanesGood is still having problems with the thumbnailing.

**Comment by batpad** [comment]
@geohacker I am having issues with the behaviour of the Back button on Android.

Steps to Reproduce:

 - Go to Edit Feature Detail
 - Click add Photo
 - Hit back button

Expected:

 - Go back to Edit Feature Detail where I was

Actual:

 - Takes me back to Explore.

Another one (which I thought worked correctly earlier):

Steps to Reproduce:

 - Go to Photos List screen
 - Click on a Photo
 - Click Back button

Expected:

 - Takes me back to Photos List screen

Actual:

 - Takes me back to Explore.

**Comment by batpad** [comment]
@geohacker to clarify, the above Steps to Reproduce are all using the Hardware Back button on Android.

**Comment by batpad** [comment]
@geohacker - To also confirm, in both the above Steps to Reproduce, using the Back button in the App produces the Expected / Desired behaviour.

**Comment by geohacker** [comment]
@batpad I want to point out that the hardware back button behaviour you are seeing is not new and not specific to this branch. It's actually how it works on all other screens. Let's figure out a fix to that in a different PR -- it might require some work :-/

@batpad @LanesGood I'd be ok if we want to move the function to add photo to the ViewFeatureDetailScreen instead of EditFeatureScreen. I defer to @LanesGood.

**Comment by LanesGood** [comment]
@geohacker reinstalling packages and upgrading yarn seemed to fix this issue.

I agree that we should move the "add photo" function to ViewFeatureDetail. At first I thought it best to keep this in the "edit" functionality, but now see that it's buried. Should we keep the add photo functionality in both screens? I would lean towards yes.

**Comment by geohacker** [comment]
feature-photo-grid

@LanesGood @batpad I added the ability to take pictures on both ViewFeatureDetail and EditFeatureDetail screen. This now consolidates the photogrid to have all these functions in a single components.

**Comment by batpad** [comment]
@geohacker this seems to work well :+1: 

Minor: it would probably be nice to show the linked feature on the photo detail page? For me, that's completely fine to do in a separate PR.

**Pull request merged**
