### PR TITLE
edit photo and traces description

### PR DESCRIPTION
**Pull request by geohacker**
Should merge #150 first.

* [x] queue description edits to photos
* [x] queue description edits to traces

### CODE REVIEW

**Comment by batpad** [comment]
@geohacker this seems to broadly work, but there's several minor issues with the behaviour of the list and indicators, etc. I realize some of these issues are likely not specific to this PR, and I don't think they all need to be solved in this PR - am happy to break out some of these into separate issues:

 - There is no indication in the list view for an item having a "pending edit" - it just shows as already uploaded, with no status of the edit.
 - The position of the edited item moves to being last in the list. I guess this is because we are sorting by last modified? Not sure the best solution, but it is a bit disorienting to go to the list, edit something, go back, and have its position moved.
 - Related to above, the items currently sort oldest to newest with newest at the bottom. I think this should be reversed to always show the newest item on top.

None of these are major, but definitely need to be fixed. Also, not sure if related to this PR, and might be something a bit silly, am getting `''file' must be a valid base64 string` when uploading new photos.

**Comment by geohacker** [comment]
@batpad except for the `file must be a valid base64 string`, all the others are known issues. We need to generally improve the way status of traces and photos are displayed so that can happen separately. 

I've not seen the base64 string warning. Where you trying on a device or emulator?

**Comment by geohacker** [comment]
The base64 issue @batpad reported is fixed in #153

**Comment by batpad** [comment]
@geohacker I agree - let's merge this and make issues for the UX issues around the list :+1:

**Pull request merged**
