### PR TITLE
Field inputs for ways

### PR DESCRIPTION
**Pull request by sethvincent**
Based on our current fields.json in the edit-ways branch, the unsupported fields right now are:

- access
- radio
- url
- networkCombo
- cycleway
- email
- tel
- identifier
- maxspeed
- onewayCheck
- restrictions
- wikidata
- structureRadio
- wikipedia

Not all of these are related to editing ways, and this PR will focus on those that are needed for ways.

### included in this pull request
so far i've been working on:

- access
- radio
- cycleway
- maxspeed
- structureRadio
- networkCombo
- onewayCheck

### should be saved for another pull request
- identifier
- wikidata
- wikipedia
- email
- tel
- url
- restrictions (turn restrictions, added to relations)

### CODE REVIEW

**Comment by sethvincent** [comment]
I added a commit that adds the onewayCheck field and that gives the access field some needed styles (it's really a field group), and also makes some revisions so that the access field works properly.

I realized that the restriction field/tag is something that is set on relations. I'm guessing that for now we're not working with relations in this editor.

**Comment by sethvincent** [comment]
Did some more testing with this today, fixed some bugs that came up when merging the edit-ways branch, and I think it's ready to review.

I believe I've tested all of these fields, though it's hard to say if I've tried every possible permutation of them.

To recap, this pull request includes changes for these fields:

- access
- radio
- cycleway
- maxspeed
- structureRadio
- networkCombo
- onewayCheck

These remaining unsupported fields should be addressed in a later pull request:

- identifier
- wikidata
- wikipedia
- email
- tel
- url
- restrictions (turn restrictions, added to relations)

**Comment by geohacker** [comment]
@sethvincent I'm noticing something weird with the fields now. I'm not entirely sure if this is introduced in this branch. For example:
* Select a primary highway
* Click edit attributes
* Click add field

image

Apart from that, this PR looks and works great for me! Thank you.

**Comment by sethvincent** [comment]
@geohacker thanks I'll look into that

**Pull request merged**
